### PR TITLE
Android NULL column issue

### PR DESCRIPTION
**Pull request by summerswell-ie**
I've just run into the same issue as platov in #43  - looking at the changes made, and subsequent changes I updated jsonArrayToStringArray to not call `jsonArray.getString` for a NULL value. Using this update, I am getting correctly inserted NULL values.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Hi, thanks for the PR. Unfortunately it's become very difficult to run the tests for this project (every few years Apple/Google change something, so the tests break, and plus Travis CI is no longer usable). I'll try to get the tests running again.

**Comment by nolanlawson** [comment]
After a lot of difficulty, I was able to get the Android tests to run locally, and to write a new test to verify that this PR fixes the issue. I'll merge and publish, but after that I'm going to mark this repo as unmaintained because I don't have the energy to keep the CI tests up to date when stuff breaks every couple years (between iOS/Android/Selenium/Appium/Cordova/Node/Java/etc it's a huge house of cards).

Thanks for fixing a 5-year-old bug, though! Nice work. :slightly_smiling_face:

**Comment by nolanlawson** [comment]
For the record, here is the test that confirms the fix (failed before this PR, succeeds after): 0b57097

**Comment by summerswell-ie** [comment]
Thanks @nolanlawson! This plugin made my life a lot easier, so its the least I could do. Thanks for the work you've put in :)

**Pull request merged**
